### ISSUE TITLE
For an arbitrary group of individuals, show the pattern at a given loci 

### ISSUE THREAD

**Issue by ebacherdom** [apriha/lineage#63]
User story:
I am a researcher with one of two grandparents, and four full siblings in my parents generation and I am attempting to recreate the missing Grandparent's DNA kit.  Following established protocols documented in Athey et al's work, I would like to identify the pattern of SNP's inherited at a given LOCI in either the actual nucleotides or a a/B output style.

Def Pattern(Input_Name, […]):
  # Pattern(RS2234095, [PW, DW, JW, SW]) --> ['TTCT' OR 'AABA']

**Comment by apriha** [comment]
Captured by updated #2.
