### ISSUE TITLE
Report on allele information at any given SNP.

### ISSUE THREAD

**Issue by ebacherdom** [apriha/lineage#65]
ALLELE SNP.

Def Allele(Input_Name, Origin='Both'):
  # Allele(RS2234095) --> 'AA'
  # Allele(RS2234095, Origin='Maternal') --> 'A'
 #Should be smart enough to determine origin is paternal if origin isn't maternal.

**Comment by ebacherdom** [comment]
This seems like derivative function o

**Comment by apriha** [comment]
Captured by updated #2.
